services:
    web:
        image: php:8.2-apache
        volumes:
          - ./src:/var/www/html
          - ./public:/var/www/html/public
        ports:
          - "80:80"
        networks:
          - backend
          - frontend
    database:
        image: mysql
        volumes:
          - db_data:/var/liv/mysql
        environment:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "prototipo"
          MYSQL_USER: "root"
          MYSQL_PASSWORD: "root"
        networks:
          - app-network
volumes:
  db_data:
networks:
  app-network:
    driver: bridge